### ISSUE TITLE
Bug in temporary file storage

### ISSUE THREAD

**Issue by daknob** [zer0rest/copypasta#2]
In
https://github.com/zer0rest/copypasta/blob/master/copypasta.sh#L22
and
https://github.com/zer0rest/copypasta/blob/master/copypasta.sh#L40
the script assumes that the `$LOCALBASEDIR` is `/tmp`, ignoring the value of the variable set in the configuration file. It should be changed to use the variable value all the time.

**Comment by zer0rest** [comment]
Hey,
Commit 1b8f4b9 fixes this.
Thanks!
