### ISSUE TITLE
SHA-1 Hashing Collisions

### ISSUE THREAD

**Issue by daknob** [zer0rest/copypasta#3]
Currently `copypasta` takes into account only the first 5 hex characters of a SHA-1 hash of the file, as per:

https://github.com/zer0rest/copypasta/blob/master/copypasta.sh#L25
https://github.com/zer0rest/copypasta/blob/master/copypasta.sh#L43

which means there are ~1M combinations (16^5). A collision within this space isn't improbable. By increasing it to 6 or 8 characters, it becomes much more unlikely (1:17M and 1:4B respectively). If post length is a concern, use of Base64 can compress the string significantly, from 16 possible values per ASCII character to 64, effectively reducing the space of the output 4x, while maintaining low probabilities of collision. Web servers will currently make the distinction between lower and upper case URLs.

**Comment by zer0rest** [comment]
Following the previous comment, commit bab6644 fixes the issue.
Thanks!
